[package]
name = "circuit-breaker"
version = "0.1.2"
edition = "2021"
authors = ["Louis Thiery <thiery.louis@gmail.com>"]
license = "Apache-2.0"
publish = false

[dependencies]
anchor-gen = { workspace = true }
anchor-lang = { workspace = true }
