[package]
name = "iot-routing-manager"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0"
publish = false

[features]
default = ["no-entrypoint"]
no-entrypoint = []

[dependencies]
anchor-gen = { workspace = true }
anchor-lang = { workspace = true }
